apps/courses/urls.py
__author__ = 'zaxlct'
__date__ = '2017/4/7 上午9:58'

from django.conf.urls import url
from .views import CourseListView, CourseDetailView, CourseInfoView, CommentView, AddCommentView, VideoPlayView

urlpatterns = [
    # 课程列表页
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),

    # 课程章节信息
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    # 评论页面

    url(r'^comment/(?P<course_id>\d+)/$', CommentView.as_view(), name='course_comment'),
    # 添加课程评论
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),

    # 播放视频
    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
__author__ = 'zaxlct'
__date__ = '2017/4/6 下午12:13'

from django.conf.urls import url

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView
from .views import TeacherListView, TeacherDetailView
urlpatterns = [
    #课程机构列表页
    url(r'^list/$', OrgView.as_view(), name='org_list'),
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),

    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),

    # 课程机构收藏/取消收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),

    # 讲师列表页
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),

    # 讲师详情页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
__author__ = 'zaxlct'
__date__ = '2017/4/9 上午11:55'

from django.conf.urls import url, include
from .views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyCourseView
from .views import MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView

urlpatterns = [
    # 用户信息
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),

    # 用户头像修改
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),

    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),

    # 修改邮箱时 发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),

    # 修改邮箱时，验证邮箱和验证码
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    # 我的课程
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),

    # 我收藏的课程机构
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),

    # 我收藏的授课讲师
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # 我收藏的课程
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name='myfav_course'),

    # 我的消息
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage'),
]

imooc/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.static import serve #处理静态文件

from imooc.settings import MEDIA_ROOT

# from django.contrib import admin
import xadmin

# from users.views import user_login
from users.views import IndexView
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView

urlpatterns = [
    url(r'^admin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    # 验证码
    url(r'^captcha/', include('captcha.urls')),

    #配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # TemplateView 只返回静态模板，不用在 views 里写逻辑
    # url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='login'),

    # 基于函数 的 View 映射 URL 方法
    # url(r'^login/$', user_login, name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),

    # 验证用户注册后，在邮件里点击注册链接
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),

    # 注册页面
    url(r'^register/$', RegisterView.as_view(), name='register'),
    # 忘记密码
    url(r'^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),

    # 退出登录
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    #用户在邮件里点击重置密码链接
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset_pwd'),

    # 重置密码表单 POST 请求
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),

    #课程机构相关 URL
    url(r'^org/', include('organization.urls', namespace='org')),

    # 课程相关 URL 配置
    url(r'^course/', include('courses.urls', namespace='courses')),

    # 用户中心 URL 配置
    url(r'^users/', include('users.urls', namespace='users')),
]

# 全局 404 页面配置（django 会自动调用这个变量）
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'


if settings.DEBUG:
    # debug_toolbar 插件配置
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))
else:
    # 项目部署上线时使用
    from imooc.settings import STATIC_ROOT
    # 配置静态文件访问处理
    urlpatterns.append(url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

apps/courses/models.py
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher
# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程机构', null=True, blank=True)
    name = models.CharField(max_length=52, verbose_name='课程名字')
    desc =  models.CharField(max_length=300, verbose_name='课程描述')
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True)
    detail = models.TextField(verbose_name='课程详情')
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=2, verbose_name='难度')
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟数)')
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图', max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否是轮播图')
    category = models.CharField(default='后端', max_length=20, verbose_name='课程类别')
    tag = models.CharField(default='', verbose_name='课程标签', max_length=10)
    youneed_konw = models.CharField(default='', max_length=300, verbose_name='课前须知')
    teacher_tell = models.CharField(default='', max_length=300, verbose_name='老师告诉你能学什么')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        verbose_name = u'轮播课程'
        verbose_name_plural = verbose_name
        # 如果不设置 proxy ，就会再生成一个 BannerCourse 数据表
        proxy = True


# 章节信息
class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name='章节')
    name = models.CharField(max_length=100, verbose_name='视频名')
    url = models.URLField(max_length=200, verbose_name='访问地址', default='www.baidu.com')
    learn_times = models.IntegerField(default=0, verbose_name='视频时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='课件名')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/course-comment.html
{% extends 'base.html' %}
{% block title %}公开课评论 - 慕学在线网{% endblock %}
{% load staticfiles %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/muke/course/learn-less.css' %}"/>
<link rel="stylesheet" href="{% static 'css/muke/course/course-comment.css' %}"/>
<link rel="stylesheet" href="{% static 'css/muke/base.css' %}">
<link rel="stylesheet" href="{% static 'css/muke/common-less.css' %}">
<link rel="stylesheet" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a> > </li>
                <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a> > </li>
                <li>课程评论</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_content %}
<div id="main">
  <div class="course-infos">
    <div class="w pr">
      <div style="height: 15px" class="path">
      </div>
      <div class="hd">
        <h2 class="l">{{ course.name }}</h2>
      </div>
      <div class="statics clearfix">
        <div class="static-item ">
          <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
          <span class="meta">难度</span>
          <em></em>
        </div>
        <div class="static-item static-time">
          <span class="meta-value">{{ course.learn_times }}分钟</span>
          <span class="meta">时长</span>
          <em></em>
        </div>
        <div class="static-item">
          <span class="meta-value"><strong>{{ course.students }}</strong></span>
          <span class="meta">学习人数</span>
          <em></em>
        </div>
      </div>
    </div>
  </div>
  <div class="course-info-main clearfix w has-progress">

    <div class="info-bar clearfix">
      <div class="content-wrap clearfix">
        <div class="content">
          <div class="mod-tab-menu">
            <ul class="course-menu clearfix">
              <li><a class="ui-tabs-active " id="learnOn" href="{% url 'courses:course_info' course.id %}"><span>章节</span></a></li>
              <li><a id="commentOn" class="active" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
            </ul>
          </div>

          <!--发布评论-->
          <div id="js-pub-container" class="issques clearfix js-form">
            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
              <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
            </div>
            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
            <p class="global-errortip js-global-error"></p>
          </div>
          <div id="course_note">
            <ul class="mod-post" id="comment-list">
              {#   课程评论  #}
              {% for user_comment in all_comments %}
              <li class="post-row">
                <div class="media">
                  <span target="_blank">
                    <img src='{{ MEDIA_URL }}{{ user_comment.user.image }}' width='40' height='40'/>
                  </span>
                </div>
                <div class="bd">
                  <div class="tit">
                    <span target="_blank">{{ user_comment.user.username }}</span>
                  </div>
                  <p class="cnt">{{ user_comment.comments }}</p>
                  <div class="footer clearfix">
                    <span title="创建时间" class="l timeago">{{ user_comment.add_time }}</span>
                  </div>
                </div>
              </li>
              {%  endfor %}

            </ul>
          </div>

        </div>
        <div class="aside r">
          <div class="bd">

            <div class="box mb40">
              <h4>资料下载</h4>
            {#  资料下载   #}
              <ul class="downlist">
                {% for course_resource in all_resources %}
                <li>
                  <span><i class="aui-iconfont aui-icon-file"></i>{{ course_resource.name }}</span>
                  <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank">下载</a>
                </li>
                {% endfor %}
              </ul>
            </div>
            <div class="box mb40">
              <h4>讲师提示</h4>
              <div class="teacher-info">
                <a href="/u/315464/courses?sort=publish" target="_blank">
                  <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80'/>
                </a>
                <span class="tit">
                  <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                </span>
                <span class="job">{{ course.teacher.work_position }}</span>
              </div>
              <div class="course-info-tip">
                <dl class="first">
                  <dt>课程须知</dt>
                  <dd class="autowrap">{{ course.youneed_konw }}</dd>
                </dl>
                <dl>
                  <dt>老师告诉你能学到什么？</dt>
                  <dd class="autowrap">{{ course.teacher_tell }}</dd>
                </dl>
              </div>
            </div>


            <div class="cp-other-learned  js-comp-tabs">
              <div class="cp-header clearfix">
                <h2 class="cp-tit l">该课的同学还学过</h2>
              </div>
              <div class="cp-body">
                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                  <!-- img 200 x 112 -->
                  <ul class="other-list">
                    {% for relate_course in relate_courses %}
                    <li class="curr">
                      <a href="{% url 'courses:course_detail' relate_course.id %}" target="_blank">
                        <img src="{{ MEDIA_URL }}{{ relate_course.image }}"  alt="{{ relate_course.name }}" />
                        <span class="name autowrap">{{ relate_course.name }}</span>
                      </a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                  <ul class="other-list">
                    <li class="curr">
                      <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                        <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                        <span class="name autowrap">Java工程师</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="clear"></div>

    </div>

  </div>
</div>
{% endblock %}

{% block custom_js %}
<script>
//添加评论
$('#js-pl-submit').on('click', function () {
    var comments = $("#js-pl-textarea").val()
    if (comments == "") {
        alert("评论不能为空")
        return
    }
    $.ajax({
        cache: false,
        type: "POST",
        url: "{% url 'courses:add_comment' %}",
        data: {course_id: {{ course.id }}, comments: comments},
        async: true,
        beforeSend: function (xhr, settings) {
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function (data) {
            if (data.status == 'fail') {
              if (data.msg == '用户未登录') {
                  window.location.href = "{% url 'login' %}";
              } else {
                  alert(data.msg)
              }
            } else if (data.status == 'success') {
                alert('评论成功！')
                window.location.reload();//刷新当前页面.
            }
        },
        error: function(error) {
          alert('ajax 失败!')
        }
    });
});
</script>
{% endblock %}

templates/usercenter-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>{% block title %}个人信息- 慕学在线网{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

  <link rel="stylesheet" href="{% static 'css/lq.datetimepick.css' %}"/>

  {% block custom_css %}
  {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
  <header>
    <div class=" header header2">
      <div class="top">
        <div class="wp">
          <div class="fl"><p>服务电话：<b>33333333</b></p></div>
          <!--登录后跳转-->
          {% if request.user.is_authenticated %}
            <div class="personal">
              <dl class="user fr">
                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
              </dl>
              <div class="userdetail">
                <dl>
                  <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                  <dd>
                    <h2>{{ request.user.nick_name }}</h2>
                    <p>{{ request.user.username }}</p>
                  </dd>
                </dl>
                <div class="btn">
                  <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                  <a class="fr" href="{% url 'logout' %}">退出</a>
                </div>
              </div>
            </div>
            <a href="{% url 'users:mymessage' %}">
              <div class="msg-num">
                <span id="MsgNum">{{ request.user.unread_nums }}</span>
              </div>
            </a>
          {% else %}
            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
          {% endif %}

        </div>
      </div>

      <div class="middle">
        <div class="wp">
          <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
          <div class="searchbox fr">
            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
              <ul class="selectMenu" id="jsSelectMenu">
                <li data-value="course">公开课</li>
                <li data-value="org">课程机构</li>
                <li data-value="teacher">授课老师</li>
              </ul>
            </div>
            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
          </div>
        </div>
      </div>


      <nav>
        <div class="nav">
          <div class="wp">
            <ul>
              <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'index' %}">首页</a></li>
              <li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
                <a href="{% url 'courses:course_list' %}">
                  公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                </a>
              </li>
              <li class="{% ifequal request.path|slice:'17' '/org/teacher/list' %}active{% endifequal %}">
                <a href="{% url 'org:teacher_list' %}">授课教师</a>
              </li>
              <li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}"><a href="{% url 'org:org_list' %}">授课机构</a></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>
</section>


<!--crumbs start-->
{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>个人信息</li>
    </ul>
  </div>
</section>
{% endblock %}

<section>
  <div class="wp list personal_list">
    <div class="left">
      <ul>
        <li class="active2"><a href="{% url 'users:user_info' %}">个人资料</a></li>
        <li><a href="{% url 'users:mycourse' %}">我的课程</a></li>
        <li><a href="{% url 'users:myfav_org' %}">我的收藏</a></li>
        <li>
          <a href="{% url 'users:mymessage' %}" style="position: relative;">
            我的消息
          </a>
        </li>
      </ul>
    </div>

    {% block right_content %}
    {% endblock %}

  </div>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
<script src="{% static 'js/unslider.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>
<script src="{% static 'js/validateDialog.js' %}"></script>
<script src="{% static 'js/deco-common.js' %}"></script>

<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/deco-user.js' %}"></script>

{% block custom_js %}
{% endblock %}

<script>
  // 课程取消收藏
  $('.jsDeleteFav_course').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "{% url 'org:add_fav' %}",
      data: {
        fav_type: 1,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });

  $('.jsDeleteFav_teacher').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "{% url 'org:add_fav' %}",
      data: {
        fav_type: 3,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });


  $('.jsDeleteFav_org').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "{% url 'org:add_fav' %}",
      data: {
        fav_type: 2,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });
</script>


<script>
  var shareUrl = '',
    shareText = '',
    shareDesc = '',
    shareComment = '';
  $(function () {
    $(".bdsharebuttonbox a").mouseover(function () {
      var type = $(this).attr('data-cmd'),
        $parent = $(this).parent('.bdsharebuttonbox'),
        fxurl = $parent.attr('data-url'),
        fxtext = $parent.attr('data-text'),
        fxdesc = $parent.attr('data-desc'),
        fxcomment = $parent.attr('data-comment');
      switch (type) {
        case 'tsina':
        case 'tqq':
        case 'renren':
          shareUrl = fxurl;
          shareText = fxdesc;
          shareDesc = '';
          shareComment = '';
          break;
        default :
          shareUrl = fxurl;
          shareText = fxtext;
          shareDesc = fxdesc;
          shareComment = fxcomment;
          break;
      }
    });
  });
  function SetShareUrl(cmd, config) {
    if (shareUrl) {
      config.bdUrl = "" + shareUrl;
    }
    if (shareText) {
      config.bdText = shareText;
    }
    if (shareDesc) {
      config.bdDesc = shareDesc;
    }
    if (shareComment) {
      config.bdComment = shareComment;
    }

    return config;
  }
  window._bd_share_config = {
    "common": {
      "onBeforeClick": SetShareUrl,
      "bdPic": "",
      "bdMini": "2",
      "searchPic": "1",
      "bdMiniList": false
    },
    "share": {
      "bdSize": "16"
    }
  };
  with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com{% static '' %}api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
</script>
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-慕学在线网{% endblock %}

{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>我的收藏</li>
    </ul>
  </div>
</section>
{% endblock %}

{% block right_content %}
<div class="right">
      <div class="personal_des Releasecont">
        <div class="head">
          <h1>我的收藏</h1>
        </div>
      </div>
      <div class="personal_des permessage">
        <div class="head">
          <ul class="tab_header messagehead">
            <li><a href="{% url 'users:myfav_org' %}">课程机构</a></li>
            <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
            <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
          </ul>

        </div>
        <div class="companycenter">
          <div class="group_list brief">
            {% for fav_course in course_list %}
            <div class="module1_5 box">
              <a href="{% url 'courses:course_detail' fav_course.id %}">
                <img width="214" height="190"
                     src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
              </a>
              <div class="des">
                <a href="{% url 'courses:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                <span class="fr">学习人数：{{ fav_course.students }}</span>
              </div>
              <div class="bottom">
                <span class="fl">{{ fav_course.course_org.name }}</span>
                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
              </div>
            </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
{% endblock %}